get_predicted: `type` vs. `predict` disambiguation
easystats/insight pull request #434
Opened 2021-09-23 18:13 UTC by vincentarelbundock

This is a PR to address issue #431  

I included a bunch of new tests, and what feels like "conservative" warnings and errors.

From my perspective, the main thing that still needs to be hashed out is what to do with the current `predict="response"` argument value. In Issue #432, there are some suggestions for different naming convention. At this stage, I would actually advocate removing it altogether for the reasons stated in the other issue. 
 
Any feedback would be much appreciated! I'm happy to make any change you deem necessary.

2021-09-28 20:37 UTC, bwiernik commented
I think let's go with "classification".

2021-09-29 00:46 UTC, vincentarelbundock commented
Thanks! For what it's worth, I also think "classification" is the best of the available options.

I force-pushed an update with the name change.

2021-09-29 01:41 UTC, DominiqueMakowski approved these changes
thanks, looks good to me :)

2021-09-29 01:43 UTC, vincentarelbundock commented
> thanks, looks good to me :)

And right as you said that, I noticed that the class-specific `get_predicted` methods had not all been updated. Sorry! Pushing the fix in 2 minutes.

2021-09-29 16:23 UTC, strengejacke requested changes

2021-09-29 16:23 UTC, strengejacke commented on R/get_predicted.R
> +#' * `"classification"` only differs from `"predict"` for binomial models where it additionally transforms the predictions into the original response's type (for instance, to a factor).
I think it should be `"prediction"` here-

2021-09-29 16:23 UTC, strengejacke commented on R/get_predicted.R
> +#' * When `predict = NULL`, alternative arguments such as `type` will be captured by the `...` ellipsis and passed directly to the `predict` method supplied by the modelling package.
I prefer adding parens when referring to functions/methods, so you may change to `predict()` here.

2021-09-29 16:23 UTC, strengejacke commented on R/get_predicted.R
> +    warning(sprintf('"%s" is not officially supported by the `get_predicted` function as a value for the `predict` argument. It will not be processed or validated, and will be passed directly to the
Please wrap in `format_message()`.

2021-09-29 16:23 UTC, strengejacke commented on R/get_predicted.R
> +      stop('The `predict` and `type` arguments cannot be used simultaneously. The preferred argument for the `get_predicted` function is `predict`. If you need to pass a `type` argument directly to t
Please wrap in `format_message()`.

2021-09-29 16:24 UTC, strengejacke commented
In general, should we have `expected` as alias for `expectation` (and likewise, `predicted` for `prediction`)? At least for me, these shorter forms are more intuitive.

2021-09-29 16:42 UTC, vincentarelbundock commented
I'm not a big fan of aliases like this. I think they just introduce complexity to save a couple letters (and all IDEs do completion). I don't have a strong preference for one version or the other (beyond concern for backward compatibility), but I do think we should stick to one canonical way.

2021-09-29 16:51 UTC, strengejacke commented
> and all IDEs do completion

Yes, but not for argument-values inside quotes, I think. But I see your point, having too many options might be confusing (or maybe we have them as undocumented options?).

2021-09-29 21:01 UTC, bwiernik commented
I agree that we probably shouldn't document too many options/aliases. But I would be okay with silently accepting `expected` and `predicted` as aliases for expectation/prediction

2021-09-29 21:22 UTC, vincentarelbundock commented
I pushed a commit with the 4 changes that @strengejacke requested. I think the the Issues I raised and proposed addressing myself should be done in a separate PR. From my perspective this is good to go, but I'm still happy to make any change you want.

FWIW, I also think we should minimize the number of undocumented aliases. It feels safer to be strict about user and to raise informative warnings and errors, rather than do automagical and undocumented changes to user input.

In the current PR, if users call `get_predicted(predict = "expected")`, they will get a warning about unknown argument value.

2021-09-29 21:23 UTC, vincentarelbundock commented
To be clear, I don't hold the views expressed above very strongly. None of this feels like a very big deal to me.

2021-09-30 00:51 UTC, DominiqueMakowski commented
> But I would be okay with silently accepting expected and predicted as aliases for expectation/prediction

Same

2021-09-30 06:23 UTC, strengejacke commented
Thanks for this PR!

2021-09-30 06:23 UTC, merged