scale message
easystats/insight pull request #591
Opened 2022-07-15 15:24 UTC by vincentarelbundock

`get_predicted()` raises an informative message when there is a matrix column in the terms. However, sometimes we supply our own `data`, and the message is still raised even if that `data` does *not* include a matrix column.

2022-07-15 22:09 UTC, bwiernik requested changes

2022-07-15 22:09 UTC, bwiernik commented on R/get_predicted_args.R
> +      any(sapply(data, function(x) "matrix" %in% class(x))),
```suggestion
      any(sapply(data, function(x) inherits(x, "matrix"))),
```

2022-07-15 22:09 UTC, bwiernik commented
One minor comment then looks good to me. You can ignore the windows test errors for the moment

2022-07-16 01:58 UTC, vincentarelbundock commented
Good call on `inherits`! I made the change.

I think the repo now "protects" the main branch, so I won't be able to merge until there's an "official" review (not sure exactly how this works).

2022-07-16 04:23 UTC, merged

2022-07-16 04:23 UTC, IndrajeetPatil commented
Thanks, @vincentarelbundock !